# Generated by Django 4.2.2 on 2023-06-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paziresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=500)),
                ('school_name', models.CharField(max_length=500)),
                ('grade', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('created_bey', models.CharField(max_length=50)),
            ],
        ),
    ]
