# Generated by Django 4.2.2 on 2023-07-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_paziresh_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziresh',
            name='GPA',
            field=models.CharField(default=20, max_length=10),
            preserve_default=False,
        ),
    ]
