# Generated by Django 4.2.2 on 2023-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paziresh_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziresh',
            name='pool',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
