# Generated by Django 4.2.2 on 2023-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_paziresh_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziresh',
            name='mahale',
            field=models.CharField(default=44, max_length=10),
            preserve_default=False,
        ),
    ]
